import { CardData } from "../_types/cardData";

// 카드 데이터
export const cards: CardData[] = [
  {
    id: 1,
    title: "캠퍼스 5K 무료나눔",
    images: [
      "/images/campusIn5K/0.jpeg",
      "/images/campusIn5K/1.jpeg",
      "/images/campusIn5K/2.jpeg",
      "/images/campusIn5K/3.jpeg",
      "/images/campusIn5K/4.jpeg",
      "/images/campusIn5K/5.jpeg",
      "/images/campusIn5K/6.jpeg",
      "/images/campusIn5K/7.jpeg",
      "/images/campusIn5K/8.jpeg",
      "/images/campusIn5K/9.jpeg",
      "/images/campusIn5K/10.jpeg",
    ],
    tag: "캠퍼스 5K 무료나눔",
    descriptions: ["따뜻한 사랑으로 아름다운 캠퍼스를 만들어 갑니다."],
    link: "/leadership",
    bgColor1: "bg-blue-100",
    bgColor2: "bg-purple-100",
  },
  {
    id: 2,
    title: "5K 청년밥차",
    images: ["/images/5kBobcha/0.jpg"],
    videos: [
      "/videos/5k_bobcha/0.MP4",
      "/videos/5k_bobcha/1.MP4",
      "/videos/5k_bobcha/2.mov",
      "/videos/5k_bobcha/3.MOV",
    ],
    tag: "5K 청년밥차",
    descriptions: ["이 나라의 대학생들을 응원합니다!"],
    link: "/campus",
    bgColor1: "bg-green-100",
    bgColor2: "bg-blue-100",
    openVideoFirst: true,
  },
  {
    id: 3,
    title: "캠퍼스 주변 5K",
    images: [
      "/images/campus5K/0.jpeg",
      "/images/campus5K/1.jpeg",
      "/images/campus5K/2.jpeg",
      "/images/campus5K/3.jpeg",
      "/images/campus5K/4.jpeg",
      "/images/campus5K/5.jpeg",
      "/images/campus5K/6.jpeg",
      "/images/campus5K/7.jpeg",
      "/images/campus5K/8.jpeg",
      "/images/campus5K/9.jpeg",
      "/images/campus5K/10.jpeg",
      "/images/campus5K/11.jpeg",
      "/images/campus5K/12.jpeg",
      "/images/campus5K/13.jpeg",
    ],
    tag: "캠퍼스 주변 5K",
    descriptions: ["아름다운 세상을 만들어가는 아름다운 대학생들"],
    link: "/meetings",
    bgColor1: "bg-yellow-100",
    bgColor2: "bg-red-100",
  },
];
